[build]
  functions = "netlify/functions"  # Directory for your serverless functions
  command = "npm run build"         # Command to build your project
  publish = "public"                # Directory to publish (for static sites)

[functions]
  directory = "netlify/functions"   # Directory for serverless functions
