[build]
  command = "npm run build"         # Command to build your project
  publish = "public"                # Directory to publish static files (if applicable)

[functions]
  directory = "netlify/functions"   # Directory for serverless functions
